use super::super::connector::Connector;
use super::super::vtparser;
use super::COMMANDS;

pub(super) fn help_main(conn: &dyn Connector) {
    let mode = super::current_mode();
    if mode != super::Mode::Root {
        help_mode(conn, mode);
        return;
    }
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("===========================================================\n");
    conn.write_str("  LodaxOS Kernel Access Terminal (katerm) v0.1\n");
    conn.write_str("===========================================================\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str("  Type ");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("help(topic)");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str(" for details on a category:\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(memory)   ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Memory inspection (dump, peek, meminfo, ...)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(tasks)    ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Process/task inspection (ps, trace, vcpus)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(sched)    ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Scheduler info (loadavg, rq)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(drivers)  ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Driver/service management\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(hardware) ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Hardware info (lapic, ioapic, cpuinfo)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(io)       ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Low-level I/O (read, write, poke)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(dump)     ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("How addresses work (presets, symbols, hex)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(symbols)  ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Symbol lookup and disassembly\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(debug)    ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Debugger (breakpoints, step, set, bt, stack)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(cpu)      ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("CPU control (poke_code, jump, force_next, recover)\n");
    conn.write_str("    ");
    conn.write_str(vtparser::sgr_fg_yellow());
    conn.write_str("help(diag)     ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Diagnostics (pagestat, slabstat, irqstat, map, hlt)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_bold());
    conn.write_str("  Quick Reference:\n");
    conn.write_str(vtparser::sgr_reset());
    for cmd in COMMANDS {
        conn.write_str("  ");
        conn.write_str(vtparser::sgr_fg_cyan());
        conn.write_str(cmd.name);
        conn.write_str(vtparser::sgr_reset());
        conn.write_str("  ");
        conn.write_str(vtparser::sgr_dim());
        conn.write_str(cmd.help);
        conn.write_str(vtparser::sgr_reset());
        conn.write_str("\n");
    }
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_dim());
    conn.write_str("  -- Address tip: type dump(heap), peek(fb), dump(kmain), peek(apic), or dump(0xFFFFFFFF81000000)\n");
    conn.write_str("  -- Safety: write, poke, drv_call, reboot ask for confirmation first\n");
    conn.write_str("  -- Use cm(mode) to switch command modes (cm mem, cm dbg, etc.)\n");
    conn.write_str(vtparser::sgr_reset());
}

fn help_mode(conn: &dyn Connector, mode: super::Mode) {
    let mode_info = super::MODE_COMMANDS.iter().find(|mc| mc.mode == mode);
    let (mode_name, cmds) = match mode_info {
        Some(mc) => (mc.name, mc.commands),
        None => return,
    };

    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Mode: ");
    conn.write_str(mode_name);
    conn.write_str(" ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");

    for &cmd_name in cmds {
        for cmd in COMMANDS {
            if cmd.name == cmd_name {
                conn.write_str("  ");
                conn.write_str(vtparser::sgr_fg_green());
                conn.write_str(cmd.name);
                conn.write_str("  ");
                conn.write_str(vtparser::sgr_reset());
                conn.write_str(cmd.signature);
                conn.write_str("\n");
                conn.write_str("                       ");
                conn.write_str(vtparser::sgr_dim());
                conn.write_str(cmd.help);
                conn.write_str(vtparser::sgr_reset());
                conn.write_str("\n");
                break;
            }
        }
    }

    conn.write_str("\n");
    conn.write_str(vtparser::sgr_dim());
    conn.write_str("  cm(..) to return to root | listmodes() to see all modes\n");
    conn.write_str(vtparser::sgr_reset());
}

pub(super) fn help_memory(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Memory Inspection ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  dump(addr, len)      ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Hex dump kernel memory.\n");
    conn.write_str("                       addr = heap, fb, apic, ioapic, code, or symbol/hex\n");
    conn.write_str("                       len  = number of bytes (default 64, max 512)\n");
    conn.write_str("                       Example: dump(heap, 128)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  peek(addr)           ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Read 64-bit value from memory.\n");
    conn.write_str("                       Same address resolution as dump.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  poke(addr, val)      ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write 64-bit to physical memory.\n");
    conn.write_str("                       Requires [y/N] confirmation.\n");
    conn.write_str("                       addr is physical address (not virtual).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  meminfo()            ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Show physical memory stats (total/used/free pages, MB).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  translate(virt_addr) ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Show physical address for a virtual address.\n");
    conn.write_str("                       Example: translate(0xFFFF800000100000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  pte(virt_addr)       ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Show page table entry with decoded flags (P, W, U, NX, etc).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  vmas()               ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List all kernel virtual memory areas.\n");
}

pub(super) fn help_tasks(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Task / Process Inspection ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  ps()                 ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List all gangs (processes):\n");
    conn.write_str("                       Shows PID, name, state, vruntime, vCPU count.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  trace(vcpu_id)       ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Full register dump of a vCPU:\n");
    conn.write_str("                       Shows RAX-R15, RIP, RFLAGS, CS, SS, RSP, ERR, VECTOR.\n");
    conn.write_str("                       Example: trace(0), trace(1)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  vcpus()              ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List all allocated vCPUs:\n");
    conn.write_str("                       Shows ID, type, state, gang, saved RIP, saved RSP.\n");
}

pub(super) fn help_sched(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Scheduler ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  loadavg()            ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Per-CPU task counts and load information.\n");
    conn.write_str("                       Shows APIC ID, online status, task count, ticks.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  rq(cpu)              ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Peek at a CPU's ready queue.\n");
    conn.write_str("                       Shows the next vCPU ID in queue + total task count.\n");
    conn.write_str("                       Example: rq(0)\n");
}

pub(super) fn help_drivers(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Drivers & Services ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  drivers()            ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List registered GDF driver packages.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  services()           ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List running services with state, vCPU, restart count.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  drv_call(name, cmd, args...)\n");
    conn.write_str("                       ");
    conn.write_str("Send a command to a driver (requires confirm).\n");
    conn.write_str("                       Example: drv_call(test_driver, 1, 0x1000, 0, 0)\n");
}

pub(super) fn help_hardware(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Hardware ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  cpuinfo()            ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List all online CPUs with APIC ID and task count.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  lapic()              ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Show LAPIC registers:\n");
    conn.write_str("                       Base address, ID, TPR, SVR, LVT timer, ISR/IRR.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  ioapic_dump(index)   ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Show IOAPIC redirection entries:\n");
    conn.write_str("                       Each pin: vector, destination APIC, trigger mode.\n");
    conn.write_str("                       Example: ioapic_dump(0)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  irq()                ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Show IOAPIC interrupt routing table (ISA->GSI->vector).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  ticks()              ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Show LAPIC timer and PIT tick counts.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  dumpcpu(cpu)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Dump state for a specific CPU.\n");
    conn.write_str("                       Example: dumpcpu(CPU0)\n");
}

pub(super) fn help_io(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Low-Level I/O ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  read(port)           ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Read a byte from an I/O port.\n");
    conn.write_str("                       Example: read(0x60)  -- PS/2 data port\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  read16(port)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Read a 16-bit word from an I/O port.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  read32(port)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Read a 32-bit dword from an I/O port.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  write(port, val)     ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write a byte to an I/O port (requires confirm).\n");
    conn.write_str("                       Example: write(0x64, 0xFE) -- reboot\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  write16(port, val)   ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write a 16-bit word to an I/O port (requires confirm).\n");
    conn.write_str("                       Example: write16(0x604, 0x2000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  write32(port, val)   ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write a 32-bit dword to an I/O port (requires confirm).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  poke(addr, val)      ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write 64-bit to physical memory (requires confirm).\n");
    conn.write_str("                       addr is physical (0x...), not virtual.\n");
}

pub(super) fn help_cpu(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== CPU Control ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  poke_code(addr, b0, b1, ...)\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("                       Write raw machine code bytes to virtual address.\n");
    conn.write_str("                       Up to 15 bytes. Uses KATERM_RECOVERY for safety.\n");
    conn.write_str("                       Example: poke_code(0x400000, 0x48, 0xC3)  -- mov rax,1; ret\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  load_code(vcpu, dst, src, len)\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("                       Copy len bytes from src to dst in a vCPU's address space.\n");
    conn.write_str("                       Both addresses must be user-mode (< HIGHER_HALF).\n");
    conn.write_str("                       Example: load_code(1, 0x400000, 0x80000, 64)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  exec_page(vcpu, phys)\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("                       Map a physical page as executable code at 0x400000 in a vCPU.\n");
    conn.write_str("                       Sets vCPU RIP to 0x400000 and schedules it.\n");
    conn.write_str("                       Example: exec_page(1, 0x100000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  jump(vcpu, addr)     ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Set vCPU's RIP to addr and resume execution.\n");
    conn.write_str("                       Sets user-mode CS/SS and schedules on least-loaded CPU.\n");
    conn.write_str("                       Example: jump(1, 0x400000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  force_next(cpu)      ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Force CPU to reschedule away from current (stuck) driver.\n");
    conn.write_str("                       Halts the current vCPU and triggers reschedule IPI.\n");
    conn.write_str("                       Example: force_next(CPU1)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  recover(cpu)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Recover CPU from hard fault / halt mode.\n");
    conn.write_str("                       Clears HALT_MODE, terminates faulted vCPU, re-enables scheduler.\n");
    conn.write_str("                       Example: recover(CPU0)\n");
}

pub(super) fn help_diag(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Diagnostics ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  pagestat()          ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Physical page allocator stats per order.\n");
    conn.write_str("                       Shows free blocks, block sizes, fragmentation.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  slabstat()          ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Kernel heap slab allocator stats.\n");
    conn.write_str("                       Shows per-cache utilization (partial/full/free slabs).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  irqstat()           ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Per-vector interrupt/exception counts.\n");
    conn.write_str("                       Shows #GP, #PF, timer, serial, IPI counts.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  map(vcpu, addr)     ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Full 4-level page table walk for a vCPU's address.\n");
    conn.write_str("                       Shows PML4 -> PDPT -> PD -> PT entries.\n");
    conn.write_str("                       Example: map(1, 0x400000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  hlt(vcpu)           ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Immediately halt a vCPU (requires confirm).\n");
    conn.write_str("                       Use when a vCPU is spinning or stuck.\n");
}

pub(super) fn help_dump(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Address Resolution ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str("  You can use any of these as the address argument:\n");
    conn.write_str("\n");
    conn.write_str("  1) ");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("Named presets");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str(" -- easy names for important locations:\n");
    conn.write_str("       code         = 0xFFFF800000100000\n");
    conn.write_str("       heap         = 0xFFFF808000000000\n");
    conn.write_str("       apic         = 0x0000FEE000000000\n");
    conn.write_str("       ioapic       = 0x0000FEC000000000\n");
    conn.write_str("       trampoline   = 0x0000000000008000\n");
    conn.write_str("\n");
    conn.write_str("  2) ");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("Symbol names");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str(" -- any function or variable in the kernel:\n");
    conn.write_str("       Example: dump(kmain), peek(idt::ticks)\n");
    conn.write_str("\n");
    conn.write_str("  3) ");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("Raw hex");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str(" -- any valid address:\n");
    conn.write_str("       Example: dump(0xFFFFFFFF80100000, 128)\n");
    conn.write_str("\n");
    conn.write_str("  dump and peek also accept phys_addr (for peek/poke).\n");
}

pub(super) fn help_symbols(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Symbols & Disassembly ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  symbols(filter)      ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List kernel symbols with addresses.\n");
    conn.write_str("                       No filter = all symbols.\n");
    conn.write_str("                       Filter = show only matching names.\n");
    conn.write_str("                       Example: symbols(kmain), symbols(apic)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  lookup(addr)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Resolve an address to its symbol + file:line.\n");
    conn.write_str("                       Example: lookup(0xFFFFFFFF80100000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  disasm(addr, count)  ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Disassemble x86-64 instructions.\n");
    conn.write_str("                       addr = preset, symbol, or hex.\n");
    conn.write_str("                       count = number of instructions (default 10).\n");
    conn.write_str("                       Example: disasm(code, 5)\n");
    conn.write_str("                       Example: disasm(0xFFFFFFFF80100000)\n");
}

pub(super) fn help_debug(conn: &dyn Connector) {
    conn.write_str(vtparser::sgr_bold());
    conn.write_str(vtparser::sgr_fg_cyan());
    conn.write_str("=== Debugger ===\n");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  set(vcpu_id, reg, val)\n");
    conn.write_str("                       ");
    conn.write_str("Modify a saved register in a vCPU's stored frame.\n");
    conn.write_str("                       reg = rax, rbx, ..., r15, rip, cs, rsp, ss, rflags\n");
    conn.write_str("                       Example: set(4, rip, 0xFFFF800000100000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  bt(vcpu_id)          ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Backtrace from vCPU's saved RBP.\n");
    conn.write_str("                       Walks the RBP chain with symbol resolution.\n");
    conn.write_str("                       Example: bt(4)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  stack(vcpu_id, n)    ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Hex dump n quadwords from vCPU's saved RSP.\n");
    conn.write_str("                       Example: stack(4, 32)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  break(addr)          ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Set software breakpoint (INT3) at address.\n");
    conn.write_str("                       Example: break(0xFFFF800000100000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  del(index)           ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Delete breakpoint by index (see bpl).\n");
    conn.write_str("                       Example: del(0)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  bpl()                ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("List all breakpoints with index, address, status.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  cont()               ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Continue a vCPU halted by breakpoint hit.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  step(vcpu_id)        ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Single-step vCPU one instruction (RFLAGS.TF).\n");
    conn.write_str("                       Example: step(4)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  watch(addr)          ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Set hardware execution breakpoint (DR0).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  cli()                ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Disable interrupts (RFLAGS.IF=0).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  sti()                ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Enable interrupts (RFLAGS.IF=1).\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  rdmsr(msr)           ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Read a Model-Specific Register.\n");
    conn.write_str("                       Example: rdmsr(0xC0000080)  -- EFER\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  wrmsr(msr, val)      ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write a Model-Specific Register (requires confirm).\n");
    conn.write_str("                       Example: wrmsr(0x8B, 0x1)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  invlpg(addr)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Flush TLB entry for a virtual address.\n");
    conn.write_str("                       Example: invlpg(0xFFFF800000100000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  read16(port)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Read 16-bit word from I/O port.\n");
    conn.write_str("                       Example: read16(0x60)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  read32(port)         ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Read 32-bit dword from I/O port.\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  write16(port, val)   ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write 16-bit word to I/O port (requires confirm).\n");
    conn.write_str("                       Example: write16(0x604, 0x2000)\n");
    conn.write_str("\n");
    conn.write_str(vtparser::sgr_fg_green());
    conn.write_str("  write32(port, val)   ");
    conn.write_str(vtparser::sgr_reset());
    conn.write_str("Write 32-bit dword to I/O port (requires confirm).\n");
}
